name: Web App CI/CD
run-name: ${{ github.actor }} is building Web App CI/CD 🚀
on:
  push:
    paths:
      - 'apps/web/**'
    branches:
      - 'main'
jobs:
  Build-Web-App:
    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: apps/web
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: pnpm/action-setup@v3 
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build    
      - run: ls -la  
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            ${{ github.sha }}
            staging
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: apps/web
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/web
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true